default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gwx_registry_api_development
  
test:
  <<: *default
  database: gwx_registry_api_test

staging:
  <<: *default
  database: gwx_registry_api_staging
  username: db_user
  password: wYWdr4cu^8#q
  host: gd14mkvw7wv5r23.crbvlq8se7oc.ap-southeast-1.rds.amazonaws.com
  port: 5432
  
production:
  <<: *default
  database: gwx_registry_api_production
  username: db_user
  password: wYWdr4cu^8#q
  host: gd184cwhzg01ezl.crbvlq8se7oc.ap-southeast-1.rds.amazonaws.com
  port: 5432
