development:
  secret_key_base:  e96e34d3f87bf638ad7e00f8d9e2bb429a739a83fdb3aa0fd34e78df95bc6276e58e6da491fbe5d4b79408810e3b1e1e7a1f972a9267e8e18adfe4f6b9bdeea1
  pk_key:  BnyF5QaqLgR7ZTAvdGqhep7zG3NnsLKy
  FCM_API_KEY: AIzaSyCiKhYx-UP85RTkIYXZTLt5cnYC0uAPkGs
  registry_private_key: fFiPoFLlrRPjZqSTPVUp6eecGDlyP6mBEmZgHf8j1Fo=
  cashier_public_key: HH2jAqAQz1ZsJ7jhQ7ntc33dRsaLKG8uKiVWsy7sXHU=
  custodian_key_secret: SwAeTII0myVv3l7I7X2SL4STi6lekhPJ
  cashier_url: http://localhost:5000/transactions
  custodian_vault_url:
  digital_win_base_url: https://go.core5server.com
  api_key: 2ekGUIwJNX
  api_id: STGGameWorksUSD
  agent_id: STGGAMEWORKS

test:
  secret_key_base:  0c6f2e7d2df5fbeec6f77c1bdd63703909e2ced06d7b0bedb6958536896ea9d32cc0484d33e171a95a6006e8d4049a9aa0f48308bd4466dfd814b698bb2774c1
  pk_key:  MUD5M7xLbNexg2HP7xMQZ44sEEM8882x
  FCM_API_KEY: AIzaSyCiKhYx-UP85RTkIYXZTLt5cnYC0uAPkGs
  registry_private_key: Afg2oBES5rtcfZTZZf2tHp_KOHXIXgES-UPH0jaLSqQ=
  cashier_public_key: kxukaTCEiU9fpEPdKiTXePvv2sco3PGWN2MMTKsNzlo=
  custodian_key_secret: KFAJ404N368W1DEnbFaBPa9CB7HeEL9o
  cashier_url: http://localhost:5000/transactions
  custodian_vault_url:
  digital_win_base_url: https://go.core5server.com
  api_key: 2ekGUIwJNX
  api_id: STGGameWorksUSD
  agent_id: STGGAMEWORKS

staging:
  secret_key_base:  77ee1a43ae728743316bddec6ce5134869a8db3317ee254429b47b879afa1f52d1fbaa575685b437ac6d62976b1f0346474cf1f3cd944bd4e3064a758a612e4c
  pk_key:  JnGguKMC55Vt98GnQ4g4dRxLqZJZhsxK
  FCM_API_KEY: AIzaSyCiKhYx-UP85RTkIYXZTLt5cnYC0uAPkGs
  registry_private_key: Kax1TdWbVaE2VI3vRsn2bfOrioLaB1vrfbWucjmEgoM=
  cashier_public_key: 455pfAXPT4Qvmjv8cLxC11VR2EVTanJ1VpsQtSDn3w4=
  custodian_key_secret: qzsoQPDs6Ayi8vqkQs9DRrlwOhkRhiHq
  cashier_url: http://3.1.204.238/transactions
  aws_access_key_id: AKIAJEGCEOYEDR3CQCTA
  aws_secret_access_key: 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
  s3_bucket_name: gwx-registry-staging
  custodian_vault_url:
  digital_win_base_url: https://go.core5server.com
  api_key: 2ekGUIwJNX
  api_id: STGGameWorksUSD
  agent_id: STGGAMEWORKS

production:
  secret_key_base:  dcad3000b5491fa92ab592eece81f9eda739242c4dbbe15b5e32ba175dd506b3bca5b05e9337afd6aa7de04de375af2b43fb26e1e890a0d3d7d2c6c8256ae7d4
  pk_key:  k9baxP2FQsVmaRLzfC2jQBszm25bCBYz
  FCM_API_KEY: AIzaSyCiKhYx-UP85RTkIYXZTLt5cnYC0uAPkGs
  registry_private_key: ccxC8-UITRhVglrfX4OeU5xHiXV9_x6S_-dSiiT52mc=
  cashier_public_key: Wt2jSMXPlreZ7VC8dnEbvfH61KNT1TQ2PEVeppJPoUQ=
  custodian_key_secret: eKC3Kwe4DgUG0fbj90pcW8ycwAPDBMrf
  cashier_url: http://3.1.204.238/transactions
  aws_access_key_id: AKIAJEGCEOYEDR3CQCTA
  aws_secret_access_key: 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
  custodian_vault_url:
